version: 0.2

artifacts:
  files:
    - '**/*'

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install pipenv
  pre_build:
    commands:
      - pipenv install
      - export VENV_HOME_DIR=$(pipenv --venv)
      - . $VENV_HOME_DIR/bin/activate
  build:
    commands:
      - echo "do nothing"
  post_build:
    commands:
      - echo "do nothing"
