version: 0.2

artifacts:
  files:
    - '**/*'

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pipenv
  pre_build:
    commands:
      - pipenv install
  build:
    commands:
      - zip -r resources.zip .
  post_build:
    commands:
      - aws s3 cp s3:flm-bot-test/SourceArti
