version: 0.2

artifacts:
  files:
    - '**/*'

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install phase at `date`
      - pip install pipenv
  pre_build:
    commands:
      - echo pre_build phase at `date`
      - pipenv install
  build:
    commands:
      - echo build phase at `date`
      - zip -r resources.zip .
  post_build:
    commands:
      - echo post_build phase at `date`
      - aws s3 cp s3:flm-bot-test/SourceArti
