Resources:
  FmlBotArtifact:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: fml-bot-artifact

  FmlLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref FmlBotArtifact
        S3Key: fml-bot/built.zip
      Description: FML bot
      FunctionName: fml-bot
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      ReservedConcurrentExecutions: 5
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/fml-bot-translate"
      Runtime: python3.7
      Timeout: 60

  LambdaScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: 'Scheduled Event'
      ScheduleExpression: 'cron(0, 3/6, *, *, ?, *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt FmlLambdaFunction.Arn
          Id: ScheduleEventId

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FmlLambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleEvent.Arn
