Resources:
  FmlLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          WEBHOOK_URL: https://hogeabc
      Code:
        S3Bucket: codepipeline-ap-northeast-1-870547711726
        S3Key: fml-bot-test2/built.zip
      Description: FML bot test
      FunctionName: fml-bot-test-cicd
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      ReservedConcurrentExecutions: 5
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/fml-bot-translate"
      Runtime: python3.7
      Timeout: 60

  LambdaScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: 'Scheduled Event'
      ScheduleExpression: 'cron(*/5, 3/6, *, *, ?, *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt FmlLambdaFunction.Arn
          Id: ScheduleEventId

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FmlLambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleEvent.Arn
