Resources:
  FmlLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
        Code:
            S3Bucket: fml-bot-test
            S3Key: built.zip
        Description: FML bot test
        FunctionName: fml-bot-test-cicd
        Handler: lambda_function.lambda_handler
        MemorySize: 128
        ReservedConcurrentExecutions: 10
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/fms-bot-role-r0r7b6hw"
        Runtime: python3.7
        Timeout: 60

  LambdaScheduleEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: 'Scheduled Event'
      ScheduleExpression: 'cron(*/5, 3/6, *, *, ?, *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt FmlLambdaFunction.Arn
          Id: ScheduleEventId

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FmlLambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaScheduleEvent.Arn
