Resources:
  LF3RIHE:
    Type: AWS::Lambda::Function
    Properties:
        Code:
            S3Bucket: fml-bot-test
            S3Key: built.zip
        Description: FML bot test
        FunctionName: fml-bot-test2
        Handler: lambda_function
        MemorySize: 128
        ReservedConcurrentExecutions: 10
        Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/fms-bot-role-r0r7b6hw"
        Runtime: python3.7
        Timeout: 60
